-- MySQL Script generated by MySQL Workbench
-- Sun Nov 19 11:55:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema whereismyhome
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `whereismyhome` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `whereismyhome` ;

-- -----------------------------------------------------
-- Table `whereismyhome`.`dongcode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`dongcode` (
  `dongCode` VARCHAR(10) NOT NULL,
  `sidoName` VARCHAR(30) NULL DEFAULT NULL,
  `gugunName` VARCHAR(30) NULL DEFAULT NULL,
  `dongName` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`dongCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`houseinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`houseinfo` (
  `aptCode` BIGINT NOT NULL,
  `buildYear` INT NULL DEFAULT NULL,
  `roadName` VARCHAR(40) NULL DEFAULT NULL,
  `roadNameBonbun` VARCHAR(5) NULL DEFAULT NULL,
  `roadNameBubun` VARCHAR(5) NULL DEFAULT NULL,
  `roadNameSeq` VARCHAR(2) NULL DEFAULT NULL,
  `roadNameBasementCode` VARCHAR(1) NULL DEFAULT NULL,
  `roadNameCode` VARCHAR(7) NULL DEFAULT NULL,
  `dong` VARCHAR(40) NULL DEFAULT NULL,
  `bonbun` VARCHAR(4) NULL DEFAULT NULL,
  `bubun` VARCHAR(4) NULL DEFAULT NULL,
  `sigunguCode` VARCHAR(5) NULL DEFAULT NULL,
  `eubmyundongCode` VARCHAR(5) NULL DEFAULT NULL,
  `dongCode` VARCHAR(10) NULL DEFAULT NULL,
  `landCode` VARCHAR(1) NULL DEFAULT NULL,
  `apartmentName` VARCHAR(40) NULL DEFAULT NULL,
  `jibun` VARCHAR(10) NULL DEFAULT NULL,
  `lng` VARCHAR(30) NULL DEFAULT NULL,
  `lat` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`aptCode`),
  UNIQUE INDEX `UNIQUE` (`buildYear` ASC, `apartmentName` ASC, `jibun` ASC, `sigunguCode` ASC, `eubmyundongCode` ASC) INVISIBLE,
  INDEX `houseinfo_dongCode_dongcode_dongCode_fk_idx` (`dongCode` ASC) INVISIBLE,
  CONSTRAINT `houseinfo_dongCode_dongcode_dongCode_fk`
    FOREIGN KEY (`dongCode`)
    REFERENCES `whereismyhome`.`dongcode` (`dongCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`member` (
  `memberId` INT NOT NULL AUTO_INCREMENT,
  `emailAccount` VARCHAR(50) NOT NULL,
  `emailDomain` VARCHAR(50) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `age` INT NOT NULL,
  `sex` VARCHAR(1) NOT NULL COMMENT '남성은 \'M\', 여성은 \'F\'',
  `authorization` INT NOT NULL COMMENT '일반 유저는 0, 관리자는 1',
  `refreshToken` VARCHAR(512) NULL,
  `createdTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedTime` DATETIME NULL DEFAULT NULL,
  `deletedTime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`memberId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`apt_view_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`apt_view_history` (
  `historyId` INT NOT NULL AUTO_INCREMENT,
  `memberId` INT NOT NULL,
  `aptCode` BIGINT NOT NULL,
  `createdTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`historyId`),
  INDEX `fk_search_history_user1_idx` (`memberId` ASC) VISIBLE,
  INDEX `fk_search_history_houseinfo1_idx` (`aptCode` ASC) VISIBLE,
  CONSTRAINT `fk_search_history_houseinfo1`
    FOREIGN KEY (`aptCode`)
    REFERENCES `whereismyhome`.`houseinfo` (`aptCode`),
  CONSTRAINT `fk_search_history_user1`
    FOREIGN KEY (`memberId`)
    REFERENCES `whereismyhome`.`member` (`memberId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`board` (
  `boardId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `content` VARCHAR(2000) NOT NULL,
  `type` INT NOT NULL,
  `memberId` INT NOT NULL,
  `dongCode` VARCHAR(10) NOT NULL,
  `hit` INT NULL DEFAULT 0,
  `createdTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedTime` TIMESTAMP NULL DEFAULT NULL,
  `deletedTime` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`boardId`),
  INDEX `fk_board_user1_idx` (`memberId` ASC) VISIBLE,
  INDEX `fk_board_dongcode1_idx` (`dongCode` ASC) VISIBLE,
  CONSTRAINT `fk_board_user1`
    FOREIGN KEY (`memberId`)
    REFERENCES `whereismyhome`.`member` (`memberId`),
  CONSTRAINT `fk_board_dongcode1`
    FOREIGN KEY (`dongCode`)
    REFERENCES `whereismyhome`.`dongcode` (`dongCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`dong_view_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`dong_view_history` (
  `historyId` INT NOT NULL AUTO_INCREMENT,
  `memberId` INT NOT NULL,
  `dongCode` VARCHAR(10) NOT NULL,
  `createdTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`historyId`),
  INDEX `fk_search_history_user1_idx` (`memberId` ASC) VISIBLE,
  INDEX `fk_dong_view_history_dongcode1_idx` (`dongCode` ASC) VISIBLE,
  CONSTRAINT `fk_dong_view_history_dongcode1`
    FOREIGN KEY (`dongCode`)
    REFERENCES `whereismyhome`.`dongcode` (`dongCode`),
  CONSTRAINT `fk_search_history_user10`
    FOREIGN KEY (`memberId`)
    REFERENCES `whereismyhome`.`member` (`memberId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`housedeal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`housedeal` (
  `dealId` BIGINT NOT NULL,
  `dealAmount` VARCHAR(20) NULL DEFAULT NULL,
  `dealYear` INT NULL DEFAULT NULL,
  `dealMonth` INT NULL DEFAULT NULL,
  `dealDay` INT NULL DEFAULT NULL,
  `area` VARCHAR(20) NULL DEFAULT NULL,
  `floor` VARCHAR(4) NULL DEFAULT NULL,
  `cancelDealType` VARCHAR(1) NULL DEFAULT NULL,
  `aptCode` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`dealId`),
  INDEX `housedeal_aptCode_houseinfo_aptCode_fk_idx` (`aptCode` ASC) VISIBLE,
  CONSTRAINT `housedeal_aptCode_houseinfo_aptCode_fk`
    FOREIGN KEY (`aptCode`)
    REFERENCES `whereismyhome`.`houseinfo` (`aptCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`member_houseinfo_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`member_houseinfo_like` (
  `aptCode` BIGINT NOT NULL,
  `memberId` INT NOT NULL,
  PRIMARY KEY (`aptCode`, `memberId`),
  INDEX `fk_houseinfo_has_user_user1_idx` (`memberId` ASC) VISIBLE,
  INDEX `fk_houseinfo_has_user_houseinfo1_idx` (`aptCode` ASC) VISIBLE,
  CONSTRAINT `fk_houseinfo_has_user_houseinfo1`
    FOREIGN KEY (`aptCode`)
    REFERENCES `whereismyhome`.`houseinfo` (`aptCode`),
  CONSTRAINT `fk_houseinfo_has_user_user1`
    FOREIGN KEY (`memberId`)
    REFERENCES `whereismyhome`.`member` (`memberId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`member_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`member_address` (
  `memberId` INT NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `dongCode` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`memberId`),
  INDEX `fk_member_address_dongcode1_idx` (`dongCode` ASC) VISIBLE,
  CONSTRAINT `fk_member_address_member1`
    FOREIGN KEY (`memberId`)
    REFERENCES `whereismyhome`.`member` (`memberId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_address_dongcode1`
    FOREIGN KEY (`dongCode`)
    REFERENCES `whereismyhome`.`dongcode` (`dongCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
